### ISSUE TITLE
pcap2erf

### ISSUE THREAD

**Issue by fmadio** [fmadio/pcap2erf#1]
need to convert a standard nanosecond PCAP into an ERF file format.

input is via stdin
output via stdout

needs to be singled threaded

**Comment by amaan-fmad** [comment]
Done - verified with Wireshark on some PCAPs with both usec/nano as magic, and with `stream_cat ... | ./pcap2erf > sample.erf`.
Supports PCAPs recorded on reverse-endianness too (i.e. different hosts).

Let me know if there's anything missing/more required! (Support for interrupt `^C` cleanly, etc.?)
